### ISSUE TITLE
Re-organize source files

### ISSUE THREAD

**Issue by ewen-lbh** [ortfo/portfoliodb#26]
A more logical splitting would be the following:

- [x] description files parsing (ok: description.go handles it)
- [x] cli commands delegation & usage (portfoliodb.go + usage.go -> main.go)
- [x] colors extraction (building.go -> colors.go)
- [x] thumbnailing (building.go -> thumbnails.go)
- [x] running the build command (commands.go + walking.go -> build.go)
- [x] media files analysis (ok: media.go handles it)
- [x] configuration parsing/resolving (configuration.go + normalize_json.go -> configuration.go)
- [x] UI-related stuff (display.go -> ui.go)
- [x] database.json replication (commands.go -> replication.go)
- [ ] configuration validation (get rid of JSON schemas, do it inside configuration.go)
- [ ] database.json validation (validation.go)

For `commands.go -> *.go` operations, gotta move the `RunCommand*` function to `*.go`, and delete `commands.go`.

Thing is, `RunCommand…` functions have too much stuff in it
